# Generated by Django 4.1.3 on 2022-12-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='check_out',
            field=models.DateField(null=True),
        ),
    ]
